dist: trusty

language: cpp

compiler: g++

os: linux

install:
  - ./ci/travis/install-linux.sh

script:
  - mkdir build 
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - mkdir TestingDir
  - ./Ample/test/test_ample
  - rm -rf TestingDir
