dist: bionic

language: shell

compiler: g++

os: linux

install:
  - ./ci/travis/install-linux.sh

script:
  - mkdir build 
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_CXX_COMPILER=g++-9
  - make -j4
  # - diff -u <(find demo -type f -name '*.cpp' -exec cat {} +) <(clang-format <(find demo -type f -name '*.cpp' -exec cat {} +)) // TODO: check clang-format
  # - mkdir TestingDir
  # - ./test/test_Ample
  # - rm -rf TestingDir
  # - cd script
  # - mkdir MyGame
  # - cd MyGame
  # - python3 ../ample.py init MyGame
  # - python3 ../ample.py build --release
  # - cd ..
  # - rm -rf MyGame
  # - pylint3 ample.py
  # - cd ..
